### ISSUE TITLE
Scorm 2004

### ISSUE THREAD

**Issue by gregdeluxee** [gabrieldoty/simplify-scorm#1]
Hi,

First, thank you very much for this scorm 1.2 run time implementation! It works really well and really simple to include to an existing LMS.

I would like to know if you worked on a version that works with the scorm 2004 version?

By the way, did you make all of the code by your own or have you been inspired by other code? It could help me to build a run time for scorm 2004.

Thank you in advance for your answer,
Greg

**Comment by gabrieldoty** [comment]
Hi Greg, thanks for the feedback!

I have not worked on a version yet for Scorm 2004, but if there was
interest in it - I would be happy to take a look at it.

The code is all mine and just based on the Scorm 1.2 reference guide here:
https://scorm.com/scorm-explained/technical-scorm/run-time/run-time-reference/

~Gabe

**Comment by gregdeluxee** [comment]
Hi,

Thanks for your fast feedback :D

Did you take a lot of time to built it ? 

I thought about maybe adapting your scorm api to fit it for scorm 2004 run time reference... As you have a good experience about it, do you think it would be a good idea ?

Thanks again !
Greg

**Comment by gabrieldoty** [comment]
Feel free to make a fork of it for Scorm 2004 - the engine took me a few
weeks to build and test, I would imagine porting it over to Scorm 2004
would probably be a much easier process

~Gabe

**Comment by gregdeluxee** [comment]
Thanks for the info.

For the moment I'll keep focus on scorm 1.2 but if I start any development for scorm 2004 I let you know ;)

Greg

**Comment by gabrieldoty** [comment]
closing, will re-open if plans to extend to 2004
