### ISSUE TITLE
SCORM API not found by the content

### ISSUE THREAD

**Issue by bryceckdev** [gabrieldoty/simplify-scorm#12]
Hi There,

I'm trying to use the simplify-scorm lib that you built - thanks for this great work btw!

My scom launcher page that load the scormAPI.js file opens the scorm content in a new window (child window) using window.open(). The scorm content in this child window is not able to find the scormAPI in the parent window.

Could you please tell me how i could achieve this?

Thank you very much!

**Comment by gabrieldoty** [comment]
Hi @bryceckdev - I see you closed this - were you able to resolve the issue?

**Comment by bryceckdev** [comment]
Hi Gabriel!
Yep, it was due to a cross-origin policy as i was opening the child frame in a different domain. I've switched parent/ child frame to the same domain then it works!
I'll keep on implementing your lib and keep you in touch if i go through any other issues.

Thanks!

**Comment by bryceckdev** [comment]
Hi Gabriel,

I reopen this issue as i've met this problem again but with  a different root  cause.

I've figured out that when launching the content from the parent window, the scormAPI is well initialized and the content's successfully launched in the child window.
But, if i close the child window and reopen the content immediatly without refreshing the parent window, it seems that the content is not able to find the scormAPI anymore and i have a **101 LMS is already finished!** error from the console.

Do you think it's due to the content API implemetation or should i implement a way to verify that the scormAPI is well initialized each time the content is launched from the parent window?

for info, i 've tested my content on scorm.com and i don't reproduce this behavior.

Thanks for your help!

**Comment by gabrieldoty** [comment]
I think you need to re-initialize SCORM every time the course window is open. I have this configuration in several of my projects, and I have hooks for start and begin that re-create the SCORM object each time. I can provide examples if you would like

**Comment by xob** [comment]
I believe the changes I made on my Scorm2004 branch would help with that. I would have to update the README though, before making that PR.

Essentially I added (among other things) an easy way to reset the API, by doing `window.API = new window.simplifyScorm.ScormAPI();`

Keep your eyes open for a pull request later today.

**Comment by bryceckdev** [comment]
Thank you @xob for the follow up, let's keep in touch.

Thanks as well @gabrieldoty , i'd appreciate if you provide me the code snippet the init the scorm api each time the content is launched from the same window context.

**Comment by bryceckdev** [comment]
Just saw the last release! Thank you guys for the great & hard work!!!!

**Comment by DenisKvashnin** [comment]
@gabrieldoty , 
I have a problem with getting information
1. Create window.API = new window.simplifyScorm.ScormAPI();
2. I uploaded json through the window.API.loadFromJSON(json)
3. After window.API.LMSInitialize();
4. after went to the page of the course through window.open

Problem: Do not get any information on the parent page. Could you send an example of use this api

**Comment by gabrieldoty** [comment]
@DenisKvashnin I am not understanding the issue. When you open your SCORM window, do you get your course? or are you not getting anything? I need more detail to understand the issue

**Comment by gabrieldoty** [comment]
@DenisKvashnin can you give an example of the `json` you are passing into the `loadFromJson` function?

**Comment by trevski** [comment]
I think I am having an similar issue.

pulling in the file at the end of the page and then getting

scormAPI.js:8 Uncaught TypeError: Cannot set property 'ScormAPI' of undefined

on page load.

As a background the SCORM course is later loaded in using a modal iframe so the course is not yet there on the page load.

Very grateful for any help.

**Comment by xob** [comment]
@trevski You are using one of the source code files. You should be using the released, compiled Simplify Scorm file, [available in the releases section](https://github.com/gabrieldoty/simplify-scorm/releases/tag/1.1.0).

**Comment by trevski** [comment]
Awesome dude, thanks rookie error.
