### ISSUE TITLE
Multiple SCORM on single page

### ISSUE THREAD

**Issue by naresh21** [gabrieldoty/simplify-scorm#18]
Was wondering if its possible to use this beautiful JS to show multiple SCORM files on single page.
**Is it possible ?**

**Comment by xob** [comment]
If you mean to have multiple SCOs playing at the same time on a single page, no, this is not possible.

However, if you mean to have one SCO playing, and then switch to another SCO, having only one active at a time, then yes it is possible with the [resetting feature for SCORM 1.2](https://github.com/gabrieldoty/simplify-scorm#resetting), also [available on the SCORM 2004 API](https://github.com/gabrieldoty/simplify-scorm#resetting-1)

Is this what you had in mind?

**Comment by naresh21** [comment]
That's what I was looking for but never thought resetting feature can be used here.
Thanks @xob ...
