### ISSUE TITLE
lastErrorCode initial value

### ISSUE THREAD

**Issue by gregdeluxee** [gabrieldoty/simplify-scorm#2]
Hello, (me again :D)

Just a little change to make to your lib,

You should change the line 19

from _self.lastErrorCode = null;
to _self.lastErrorCode = '0';

as the "No error" code is 0 from the runtime reference.

There is some software that ask for the last error code during the initialization state and throw an error if the initial lastErrorCode is null. It might be helpful for you if you're still using your library :)

I didnt make a fork as I am not used to contribute and I don't really have time to check how to do that so I prefer to let you know the issue.

Thank again for sharing this code... Works great !

Greg

**Comment by gabrieldoty** [comment]
Thanks @gregdeluxee  - I have updated the repo
