### ISSUE TITLE
Compatibility with rise 360

### ISSUE THREAD

**Issue by sainag** [gabrieldoty/simplify-scorm#24]
Hi,

Can someone advise, if this is compatible with the scorm packages published with Rise 360?

Thanks
Sai

**Comment by xob** [comment]
According to [Rise 360's FAQ](https://articulate.com/support/article/Articulate-360-FAQs-Rise):
> Can Rise 360 courses be hosted and tracked in a learning management system (LMS)?
> Yes. You can export Rise 360 courses for AICC, SCORM 1.2, SCORM 2004, and Tin Can API (xAPI) learning management systems. Just open your Rise 360 course for editing, click Export in the upper right corner of the screen, and choose an LMS specification.

Since Simplify Scorm implements SCORM 1.2 and SCORM 2004, yes, it is compatible with SCORM packages published with Rise 360, as long as SCORM 1.2 or SCORM 2004 is chosen as the export format.

**Comment by sainag** [comment]
Hi,
I know that it will work with the given scorm specification as I have been using the plugin with various scorn packages published with isprig, storyline and captivate etc.. however, the exported scorm package with rise 360 doesn’t seem to fire any events with all the settings set when publishing.

Let me know if you have tried using it with rise360 output.
@gabrieldoty can you please advise on this.

Thanks
Sai

**Comment by xob** [comment]
That sounds more like a question for Rise 360 support rather than Simplify Scorm. If the SCO generated from Rise 360 doesn't trigger any events in Simplify Scorm, and other SCOs do, then it appears to be a problem with how Rise 360 consumes a SCORM API, not a problem with Simplify Scorm.

**Comment by sainag** [comment]
You may be right. I'll raise an issue with them. Thanks.

**Comment by Pioda** [comment]
In terms of Rise or Storyline or other Articulate SCORM Software: Each course their software renders contains a folder called "lms" toplevel. In there they host a "scormdriver.js" containing alot of configuration for their course. They recently changed a field "forced_commit_time" to 0 (prev. 60.000). This setting advises their courses to not auto commit every x seconds. In older versions the config file is named "configuration.js" i believe. @sainag after setting the value of forced_commit_time to something over than 0 you should see regular repeating commits.
