### ISSUE TITLE
scorm player php mysql

### ISSUE THREAD

**Issue by gheeenrique** [gabrieldoty/simplify-scorm#3]
Hello friends,
I'm trying to develop a scorm player that sends to mysql, has anyone done anything like this? Thank you.

**Comment by gabrieldoty** [comment]
Hello, this should work ideally for you, in the documentation should be a description about how to serialize the scorm value into JSON which should be easily stored into a DB, let me know if you have any questions

**Comment by gheeenrique** [comment]
I can not get a response in scorm exported by SAP WPB, I run the course but I do not have JSON response.

**Comment by gabrieldoty** [comment]
You have to manually get the response on the course exit or on the finish event by calling API.cmi.toJSON();
