### ISSUE TITLE
is there any way to get scrom version ?

### ISSUE THREAD

**Issue by houssemaydi** [gabrieldoty/simplify-scorm#45]

**Comment by brianmcaudill** [comment]
The version is in the imsmanifest.xml file. 
`<metadata>
      <schema>ADL SCORM</schema>
      <schemaversion>1.2</schemaversion><-- here, this is a SCORM 1.2  manifest
   </metadata>`
   
` <metadata>
      <schema>ADL SCORM</schema>
      <schemaversion>CAM 1.3</schemaversion><-- here, this is a SCORM 2004  manifest
   </metadata>`  
If you have access to the course package you will find it there. If you don't have access to the course package you can use the developer console in the browser to look in the topmost window (or in a popup if the course is launched in a popup) for an object called API or API_1484_11. If you find API then it is SCORM 1.2. If you find API_1484_11 then it is SCORM 2004. One more thing that you can look at or if you find both API and API_1484_11 (this is very uncommon) is look to see if the data is being sent to the LMS using LMSSetValue() or SetValue(). If it is LMSSetValue() then the course is SCORM 1.2. If it is SetValue() the course is SCORM 2004. 

I think that covers it.

**Comment by houssemaydi** [comment]
@brianmcaudill I appreciate your time and effort in thoroughly understanding the issue and proposing an effective solution. 
Thank you for your assistance.
