### ISSUE TITLE
setting initial values

### ISSUE THREAD

**Issue by ddamicotam** [gabrieldoty/simplify-scorm#6]
Hi there!

First of all thanks very much for this library, it's super super helpful.

Second, I was wondering if you could expand upon the explanation in the docs of how to set the initial values in API.cmi.

Right now I'm pulling in the API code, then doing my sets on window.API.cmi, then allowing my content to init and call LMSInitialize. What I'm finding is the sets for read-only values flow through your setter implementation, which calls API.throwSCORMError, which results in the values not getting set, and in the content encountering the error code when it init's, and everything comes crashing down from there.

That's exactly what I would expect if I was a piece of content trying to do this, but acting as the "LMS" in this case it seems like something I'm supposed to be able to do? I feel like I must be missing something super-obvious here, so I apologize in advance if that's the case.

Thanks again!

**Comment by gabrieldoty** [comment]
Thanks for the feedback! Can you elaborate on which items you are running into this on?

This has been implemented exactly as the Scorm spec states, even though there are some items which don't make sense, i.e. any item that is write only doesn't make sense to me personally as any attempt to access those variables throw an error. 

That being said - all the data that should be necessary for a course to resume from a particular point should all be stored in the "suspend_data" generally this is the only thing that I set. 

If you give me more concrete examples I can offer more guidance

**Comment by ddamicotam** [comment]
Thanks so much for the quick response!

So, on start I pull back my persisted copy of cmi, and then do

```javascript
window.API.cmi.core.student_id = '123';
window.API.cmi.suspend_data = incomingCmi.suspend_data;
```

and then later initialize. The set to student_id lands me in

```javascript
set student_id(student_id) {
    API.throwSCORMError(API, 403);
},
```

at ln. 592. The value I tried to set into student_id isn't there, since we hit the error and didn't do the set, and then when LMSInitialize runs, LMSGetLastError is still returning that 403 and the content tries to handle the error.

Exactly as you say, though, If I remove the set to student_id and only set suspend_data, I never hit the issue because no 'read only' error is ever thrown.

I was thinking that since your example specifically references a read-only value that setting initial values for them would be possible, but I can see how it might be a bear to implement and if this is just a limitation of the library that's fine by me! :)

Thanks!

**Comment by xob** [comment]
I also ran into this problem, and while I haven't spent any time on this yet, my initial idea to remedy this issue would be to add a method called "fromJSON" to complement the "toJSON" method, to load data from a JSON object.

The method could work similarly to "toJSON", where it would set a variable to true to temporarily allow writing to restricted attributes.

**Comment by gabrieldoty** [comment]
I see - yes - I believe there should be a way to set these before initialization. This makes much more sense then the scorm spec. I will make an update that allows you to set these before init!

**Comment by gabrieldoty** [comment]
I am thinking that anything that is readonly should be able to be set as long as currentState != STATE_INITIALIZED

Thoughts?

**Comment by xob** [comment]
That would work. Not sure if it would violate SCORM standards or not, though.

**Comment by gabrieldoty** [comment]
They are very vague on it. I suspect that is how they intended it - looking the documentation - this is what they say about student_id: 

"LMS is responsible based on student registration"

**Comment by gabrieldoty** [comment]
I have updated master with updates with the discussed updates, happy coding!

**Comment by xob** [comment]
@gabrieldoty Code review: Line 605, you accidentally left a `debugger` in there.

**Comment by ddamicotam** [comment]
Thanks SO much! I pulled the updates this morning and they have resolved the issue.

Not sure if this was an intentional change or something that was unintentionally left in from the work on the updates, but FYI this also changed ln. 35 so that the log level is now set to debug to default.

Thanks again!

**Comment by gabrieldoty** [comment]
@ddamicotam no problem! The default state should have been changed to "ERROR" by default  now - which I believe is what most people should have running in production, I did update docs the docs with that change as well
